main_page/urls.py
from . import views
from django.urls import path,include
app_name = "player"
urlpatterns = [
    path('delete_card/<int:pk>/',views.CardDelete.as_view()),
    path('update_card/<int:pk>/', views.CardUpdate.as_view()),
    path('create_card/',views.CardCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/', views.CardDetail.as_view()),
    path('', views.CardList.as_view()),
    path('team_list/', views.TeamList.as_view()),
    path('search/',views.search, name='search'),
    #path('', views.index), FBV방식
    #path('<int:pk>/', views.single_player_card),
]

soccer_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_page/', include('main_page.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]


urlpatterns += static(settings.MEDIA_URL,
                        document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/models.py
from django.db import models


class Team(models.Model): # 기존에서 팀id를 pk로 받겠습니다.
    teamName = models.CharField(max_length=50)
    coachName = models.CharField(max_length=10)
    homeStadium = models.CharField(max_length=20)
    region = models.CharField(max_length=10)
    rank = models.IntegerField()

    head_image = models.ImageField(upload_to='main_page/images/%Y/%m/%d', blank=True)
    category = models.ForeignKey("Category", null=True, on_delete=models.SET_NULL, blank=True,db_column='slug')        # 외래키키
    def __str__(self):
        return self.teamName

    def get_absolute_url(self):
        return f'/main_page/category/{self.category.slug}/'

class Category(models.Model): # 팀별 카테고리 생성
    categoryName = models.OneToOneField(Team, on_delete=models.CASCADE, related_name="organize", unique=True)  # 카테고리 이름
    slug = models.SlugField(max_length=50, unique=True, allow_unicode=True) # slug 필드는 사람이 읽을 수 있는 텍스트로 고유 url을 만들때 사용

    def __str__(self):
        return str(self.categoryName)

    def get_absolute_url(self):
        return f'/main_page/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories' # 카테고리 이름 변경





class Player(models.Model):

    name = models.CharField(max_length=10)
    position = models.CharField(max_length=5)
    pass_success_rate = models.IntegerField()
    shoot_success_rate = models.IntegerField()
    height = models.IntegerField(default=170)
    weight = models.IntegerField(default=60)
    nationality = models.CharField(default="kor", max_length=10)
    birthdate = models.DateField(blank=True, null=True, default='2000-01-01')
    jersey_number = models.IntegerField(blank=True, null=True)


    head_image = models.ImageField(upload_to='main_page/images/%Y/%m/%d', blank=True)

    team_name = models.ForeignKey(Team, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, blank=True)        # 외래키키

    def __str__(self):
        return f'[{self.pk}] {self.name}'

    def get_absolute_url(self):
        return f'/main_page/{self.pk}/'

single_pages/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.shortcuts import render
from .models import Player, Category, Team
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django import forms
from . import models
from django.core.paginator import Paginator
#CBV 방식
class SearchForm(forms.Form):
    '''Search Form Definition'''
    name = forms.CharField(required=False)
    shoot_rate = forms.IntegerField(required=False)
    shoot_rate_lte = forms.IntegerField(required=False)
    position = forms.CharField(required=False)
    nationality = forms.CharField(required=False)
    team_type = forms.ModelChoiceField(
        empty_label="Any Kind", queryset=models.Team.objects.all(), required=False
    )
def search(request):
    #  request.GET를 통해 모든 값을 기억
    form = SearchForm(request.GET)
    if form.is_valid():
        player_name = form.cleaned_data.get("name")
        shoot_rate = form.cleaned_data.get("shoot_rate")
        shoot_rate_lte = form.cleaned_data.get("shoot_rate_lte");
        position = form.cleaned_data.get("position")
        nationality = form.cleaned_data.get("nationality")
        team_type = form.cleaned_data.get("team_type")

        #search argument
        filter_args = {}
        if player_name != '':
            print('player not none')
            filter_args["name"] = player_name
        if position != '':
            print('position not none')
            filter_args["position"] = position
        if nationality != '':
            print('nationality not none')
            filter_args["nationality"] = nationality
        if team_type is not None:
            print(team_type)
            filter_args["team_name_id"] = team_type
        if shoot_rate is not None:
            filter_args["shoot_success_rate__gte"] = shoot_rate
        if shoot_rate_lte is not None:
            filter_args["shoot_success_rate__lte"] = shoot_rate_lte

    player = models.Player.objects.filter(**filter_args)
    context = {"form": form, "player":player}
    return render(request, 'main_page/search.html', context)


class CardDelete(DeleteView):
    model = Player
    success_url = '/main_page/' # 성공시 돌아갈 링크
class CardUpdate(UpdateView):
    model = Player
    fields = [
        'name', 'position', 'pass_success_rate','shoot_success_rate',
        'height', 'weight', 'nationality', 'birthdate', 'jersey_number',
        'head_image','team_name', 'category'
    ]
    template_name = 'main_page/card_update_form.html'

class CardCreate(CreateView):
    model = Player
    fields = [
        'name', 'position', 'pass_success_rate','shoot_success_rate',
        'height', 'weight', 'nationality', 'birthdate', 'jersey_number',
        'head_image','team_name', 'category'
    ]

    # def form_valid(self, form):
    #     current_user = self.request.user # 웹사이트의 방문자
    #     form.instance.category = str(form.instance.team_name)
    #     return super(CardCreate, self).form_valid(form)
class CardList(ListView): # FBV방식의 index를 대체하는 클래스
    model = Player
    ordering = '-name'
    paginate_by = 12
    def get_context_data(self, **kwargs):
        context = super(CardList, self).get_context_data()  #오버라이딩
        context['categories'] = Category.objects.all() # 모든 카테고리를 가져와 키에 연결해담음
        context['no_category_card_count'] = Player.objects.filter(category=None).count() #카테고리가 지정되지않은 선수를 키에 담는다

        return context


class CardDetail(DetailView):
    model = Player

    def get_context_data(self, **kwargs):
        context = super(CardDetail, self).get_context_data()  #오버라이딩
        context['categories'] = Category.objects.all() # 모든 카테고리를 가져와 키에 연결해담음
        context['no_category_card_count'] = Player.objects.filter(category=None).count() #카테고리가 지정되지않은 선수를 키에 담는다
        return context

def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류',
        player_list = Player.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        player_list = Player.objects.filter(category=category)
    return render(
        request,
        'main_page/player_list.html',
        {
            'player_list': player_list,
            'categories': Category.objects.all(),
            'no_category_card_count': Player.objects.filter(category=None).count(),
            'category': category,
        }
    )

class TeamList(ListView): # FBV방식의 index를 대체하는 클래스
    model = Team
    ordering = 'rank'

# FBV 방식
# def index(request):  ///class CardList로 대체
#     player = Player.objects.all().order_by('-name')
#     return render(
#         request,
#         'main_page/player_list.html',
#         {
#             'player': player,
#         }
#     )
#
# def single_player_card(request,pk): ///class CardDetail 대체
#     player=Player.objects.get(pk = pk)
#
#     return render(
#         request,
#         'main_page/player_detail.html',
#         {
#             'player':player
#         }
#     )
#

single_pages/views.py
from django.shortcuts import render

# Create your views here.

main_page/templates/main_page/base.html
<!Doctype html>
{% load static %}
<html lang = "ko">
<head>
    <meta charset = "UTF-8">
    <title>Main page</title>
    <link href="{% static 'main_page/bootstrap/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <title> {%  block head_title %}Blog{% endblock %}</title>
</head>
<body>
    {% include 'main_page/navbar.html' %}
    <div class="container my-3">
        <div class="row">
            <div class="col-md-4 col-lg-3">
                <!-- Categories widget-->

                <!-- Side widget-->
                <div class="card mb-4" id="categories-card">
                    <div class="card-header"> 클럽 </div>
                    <div class="card-body">
                        <div class="row">

                                <ul>
                                    {% for category in categories %}
                                    <li><a href="{{ category.get_absolute_url }}">
<!-- -->
                                            {{ category.categoryName }} ({{ category.player_set.count }})
                                        </a>
                                    </li>
                                    {% endfor %}
                                    <li style="display:none;"><a href="/main_page/category/no_category">
                                        미분류 ({{ no_category_card_count }})
                                    </a>

                                    </li>
                                </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-lg-9" id="main-area">
                <!-- Card Post -->
{% block main_area %}

{% endblock %}
        </div>

            </div>
        </div>
{% include 'main_page/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
</body>
</html>

main_page/templates/main_page/base_full_width.html
<!DOCTYPE html>
<html lang = "ko">
<head>
    <meta charset="UTF-8">
{% load static %}
    <link href="{% static 'main_page/bootstrap/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <title> {%  block head_title %} Blog {% endblock %}</title>
    <style> {% block style_block %} {% endblock %}</style>

</head>
<body>
    {% include 'main_page/navbar.html' %}
    <div class="container my-3">
        <div class="row">
            <div class="col-12" id="main-area">
              {% block main_area %}
              {% endblock %}
            </div>
        </div>
    </div>
{% include 'main_page/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
</body>
    <script> {% block script_block %} {% endblock %}</script>
</html>

main_page/templates/main_page/card_update_form.html
{% extends 'main_page/base_full_width.html' %}
{% block head_title %} Edit Card - SoccerDB {% endblock %}

{% block main_area %}
    <h1> Edit player Card</h1>
    <hr/>
<!--
    form태그는 기록한 값을 서버로 보냄 -enctype은 파일도 전송하겠다는 의미 원래는 action까지 처리해주어야하는데 장고는 알아서 처리해줌
    csrf_token은 csrf공격으로부터 보호하기 위해 제공하는 기능
-->
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>

            {{ form }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>


    </form>
{% endblock %}

main_page/templates/main_page/footer.html
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 데이터 처리 시스템 조별과제 TEAM DEPPO</p></div>
</footer>

main_page/templates/main_page/index.html
<!Doctype html>
<html lang = "ko">
<head>
    <meta charset = "UTF-8">
    <title>Main page</title>
</head>
<body>
    <h1> main page</h1>
{% for p in player %}
    <a style="text-decoration: none;  color: gray;" href="{{ p.get_absolute_url }}"><div>
        <h3>이름: {{ p.name }}</h3>
        <h2>포지션: {{ p.position}}</h2>
        <p>구단명: {{ p.team_name }}</p>
    </div>
    </a>
    <hr>
{% endfor%}
</body>
</html>

main_page/templates/main_page/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="container">
            <a class="navbar-brand" href="/main_page/">DEPPO 프로젝트</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/main_page/">선수 리스트</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/main_page/team_list/">클럽 리스트</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/main_page/search/?name=%EC%9D%B4%EA%B8%B0%ED%98%81&shoot_rate=&shoot_rate_lte=&position=&nationality=&team_type=">선수 검색</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

main_page/templates/main_page/pagination.html
                    <!-- Pagination -->
                    {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?&page={{ page_obj.previous_page_number }}">이전</a>

                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                            </li>
                            {% endif %}
                            {% for page_number in page_obj.paginator.page_range %}
                            {% if page_number == page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% else %}
                            <li class="page-link">
                                <a class="page-item" href="?&page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?&page={{ page_obj.next_page_number }}">다음</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                            </li>
                            {% endif %}
                      </ul>
                    </nav>
                    {% endif %}

main_page/templates/main_page/player_confirm_delete.html
{% extends 'main_page/base_full_width.html' %}
{% block head_title %} Delete Card - SoccerDB {% endblock %}

{% block main_area %}
    <h1> Delete player Card</h1>
    <hr/>
<!--
    form태그는 기록한 값을 서버로 보냄 -enctype은 파일도 전송하겠다는 의미 원래는 action까지 처리해주어야하는데 장고는 알아서 처리해줌
    csrf_token은 csrf공격으로부터 보호하기 위해 제공하는 기능
-->
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>

            <h1>정말로 {{ player.name }}을 삭제하실 건가요?</h1>
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>


    </form>
{% endblock %}

main_page/templates/main_page/player_detail.html
{% extends 'main_page/base.html' %}
{% block main_area %}

{% block head_title %}
    {{ player.name }} - Blog
{% endblock %}
    <nav> <a href="/main_page/">돌아가기</a>  </nav>
    <div>
        {% if player.category %}
            <span class="badge badge-secondary float-right"> {{ player.category }}</span>
            {% else %}
            <span class="badge badge-secondary float-right"> 미분류 </span>
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h1> {{player.name}}</h1>
                </div>
                {% if player.head_image %}
                <div class="col-lg-4">
                    <img class="float-left" style="width:100px"src="{{ player.head_image.url }}" alt="{{ p }} head image">
                </div>
                {% else %}
                <div class="col-lg-4">
                    <img style="height: 264px" class = "card-img-top" src="https://portal.kleague.com/images/portal/img-nonepicture-userprofil.png">
                </div>
                {% endif %}
            </div>
        </div>
        <hr/>
        <a class="btn btn-info btn-sm float-right" href="/main_page/update_card/{{player.pk}}/" role="button">
            <i class="fas fa-pen"> Edit Card</i>
        </a>
        <a class="btn btn-danger btn-sm float-right mr-3" href="/main_page/delete_card/{{player.pk}}/" role="button"> Delete Card</a>
        <h3>포지션: {{player.position }}</h3>
        <h3>구단명: {{ player.team_name }}</h3>
        <p> 체중: {{ player.weight }}</p>
        <p> 신장: {{ player.height }}</p>
        <p> 국적: {{ player.nationality }}</p>
        <p> 등번: {{ player.jersey_number }}</p>
        <p> 패스 성공률: {{ player.pass_success_rate }} </p>
        <p> 슛 성공률: {{player.shoot_success_rate}} </p>


    </div>

{% endblock %}

main_page/templates/main_page/player_form.html
{% extends 'main_page/base_full_width.html' %}
{% block head_title %} Create Card - SoccerDB {% endblock %}

{% block main_area %}
    <h1> Create new player Card</h1>
    <hr/>
<!--
    form태그는 기록한 값을 서버로 보냄 -enctype은 파일도 전송하겠다는 의미 원래는 action까지 처리해주어야하는데 장고는 알아서 처리해줌
    csrf_token은 csrf공격으로부터 보호하기 위해 제공하는 기능
-->
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>

            {{ form }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>


    </form>
{% endblock %}

main_page/templates/main_page/player_list.html
{% extends 'main_page/base.html' %}
{% block main_area %}
                <!-- Card Post -->
{% if category %}
                <h1> {{ category }} </h1>
{% else %}
                <h1>Player List</h1>
                <a href="/main_page/create_card/"><button type="button" class="btn btn-outline-primary btn-circle">선수 생성</button></a>
{% endif %}
                <div class="row">
{% if player_list.exists %}

{% for p in player_list %}
                    <div class="col-sm-3">
                        <div style="width: 200px" class="card m-4" id="card-{{ p.pk }}">
    {% if p.head_image %}
                            <a href="#!" ><img class="card-img-top"  src="{{ p.head_image.url }}" alt="{{ p }} head image" /></a>
        {% else %}
                            <img style="height: 264px" class = "card-img-top" src="https://portal.kleague.com/images/portal/img-nonepicture-userprofil.png">
    {% endif%}
                            <div class="card-body">

                                <h2 class="card-title h4">{{ p.name }}</h2>
{% if p.category %}
                                <span class="badge badge-secondary">{{ p.category }}</span>
        {% else %}
                                <span class="badge badge-secondary"> Unknown</span>
    {% endif %}
                                <p class="card-text">포지션: {{p.position}} <br> 구단명: {{p.team_name}}</p>

                                <a class="btn btn-primary" href="{{ p.get_absolute_url }}">상세 정보 →</a>
                            </div>
                        </div>
                    </div>

{% endfor%}

{% else %}
                    <h3> 선수 명단이 존재하지 않습니다. </h3>
{% endif%}
{% include 'main_page/pagination.html' %}
                </div>

{% endblock %}

main_page/templates/main_page/search.html
{% extends 'main_page/base_full_width.html' %}
{% block head_title %} Search Card - SoccerDB {% endblock %}
{% block style_block %} #id_name{width: 200px;}{% endblock %}

{% block main_area %}
    <h1>선수 검색</h1>
    <br><hr>
    <p>무료 서버 특성상 속도가 원활하지 않아 검색이 원할하지 않습니다.</p>
    <form method="get"  action="{% url "player:search" %}">
        {{form}}
        <br>
        <br>
        <button class="btn btn-outline-primary btn-circle float-right">Search</button>
    </form>

                <div class="row">
{% if player %}
{% for p in player %}
                    <div class="col-sm-3">
                        <div style="width: 200px" class="card m-4" id="card-{{ p.pk }}">

    {% if p.head_image %}
                            <a href="#!" ><img class="card-img-top"  src="{{ p.head_image.url }}" alt="{{ p }} head image" /></a>
        {% else %}
                            <img style="height: 264px" class = "card-img-top" src="https://portal.kleague.com/images/portal/img-nonepicture-userprofil.png">
    {% endif%}
                            <div class="card-body">

                                <h2 class="card-title h4">{{ p.name }}</h2>
{% if p.category %}
                                <span class="badge badge-secondary">{{ p.category }}</span>
        {% else %}
                                <span class="badge badge-secondary"> Unknown</span>
    {% endif %}
                                <p class="card-text">포지션: {{p.position}} <br> 구단명: {{p.team_name}}</p>

                                <a class="btn btn-primary" href="{{ p.get_absolute_url }}">상세 정보 →</a>
                            </div>
                        </div>
                    </div>
{% endfor%}
{% else %}

<div class="container text-center m-5"><h2>검색결과가 존재하지 않습니다. 다시 검색해주세요.</h2></div>

{% endif %}
                    </div>
{% endblock %}

{% block script_block %}
<!-- placeholder -->
inputID = document.querySelector('#id_name'); inputID.placeholder = '이름을 입력해주세요';
shootID = document.querySelector('#id_shoot_rate'); shootID.placeholder = '슛 성공률 최솟값';
shootLteID = document.querySelector('#id_shoot_rate_lte'); shootLteID.placeholder = '슛 성공률 최댓값';


<!-- bootstrap style -->
comboInput = document.querySelector('#id_team_type'); comboInput.className += 'custom-select';
inputs = document.querySelectorAll('input');
for (let element of inputs) {
    element.className += 'form-control';
}

{%  endblock %}

main_page/templates/main_page/single_player_card.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ player.name}} - 축구 DB</title>
</head>
<body>
    <nav> <a href="/main_page/">돌아가기</a>  </nav>
    <div>
        <h1> {{player.name}}</h1>
        <h3> 포지션: {{player.position }} 구단명: {{ player.team_name }}</h3>
        <p> 패스 성공률: {{ player.pass_success_rate }} </p>
        <p> 슛 성공률: {{player.shoot_success_rate}} </p>
    </div>
</body>
</html>

main_page/templates/main_page/team_list.html
{% extends 'main_page/base_full_width.html' %}

{% block head_title %} Team Lists - SoccerDB {% endblock %}

{% block main_area %}
<div class="container">
    <h1> 명예의 전당</h1>


    {% if team_list.exists%}

        {% for t in team_list %}

            {% if t.rank == 1 %}
                <div class="row">
                    <div  class="col-lg-4"></div>
                    <div style="border:none; background-color:rgba(0, 0, 0, 0);"  class="card m-4 col-lg-4 text-center" id="team-{{ t.pk }}">
                        <a style=" text-decoration: none;" href="{{ t.get_absolute_url }}">
                            <div><img class="text-center" style="width:60px"src="https://cdn-icons-png.flaticon.com/512/3132/3132778.png"/></div>
                        {% if t.head_image %}
                            <div><img style="width:60px" class = "card-img-top text-center" src="{{ t.head_image.url }}" alt="{{ t }} head image"></div>
                    {% else %}
                    {% endif %}
                            <div class="card-body">  {{ t.teamName }}</div>
                        </a>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
                {% elif t.rank == 2 %}
                <div class="row">
                    <div class="col-lg-2"></div>
                        <div style="border:none" class="card m-6 col-lg-4 text-center" id="team-{{ t.pk }}">
                            <a style=" text-decoration: none;" href="{{ t.get_absolute_url }}">
                            <div><img class="text-center" style="width:60px" src="https://cdn-icons-png.flaticon.com/512/2583/2583319.png"/></div>
                            {% if t.head_image %}
                            <div><img style="width:60px" class = "card-img-top text-center" src="{{ t.head_image.url }}" alt="{{ t }} head image"></div>
                            {% else %}
                            {% endif %}
                            <div class="card-body">  {{ t.teamName }}</div>
                            </a>
                        </div>
                {% elif t.rank == 3 %}
                    <div style="border:none" class="card m-6 col-lg-4 text-center" id="team-{{ t.pk }}">
                        <a style=" text-decoration: none;" href="{{ t.get_absolute_url }}">
                        <div><img class="text-center" style="width:60px"src="https://cdn-icons-png.flaticon.com/512/2583/2583434.png"/></div>
                            {% if t.head_image %}
                            <div><img style="width:60px" class = "card-img-top text-center" src="{{ t.head_image.url }}" alt="{{ t }} head image"></div>
                            {% else %}
                            {% endif %}
                        <div class="card-body">  {{ t.teamName }}</div>
                        </a>
                    </div>
                    <div class="col-lg-2"></div>
                </div>

            {% endif %}
        {% endfor %}
<hr>
        <h1> 팀 명단</h1>
        <div class="row">
        {% for t in team_list %}

                <div style="border:none" class="card m-4 col-sm-3 text-center" id="team-{{ t.pk }}">
                    <a style=" text-decoration: none;" href="{{ t.get_absolute_url }}">
                        {% if t.head_image %}
                        <div><img style="width:60px" class = "card-img-top text-center" src="{{ t.head_image.url }}" alt="{{ t }} head image"></div>
                        {% else %}
                        {% endif %}
                    <div class="card-body">  {{ t.teamName }}</div>
                    </a>
                </div>

        {% endfor %}
        </div>









    {% else %}
        <h1> 팀 명단이 존재하지 않습니다... ㅠㅠ </h1>
    {% endif%}
</div>
{% endblock %}